//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSR_3_Kan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2
    {
        public int id_table_2 { get; set; }
        public Nullable<int> id_table_1 { get; set; }
        public string C_table_2 { get; set; }
    
        public virtual Table_1 Table_1 { get; set; }
    }
}
